// svelte/VoxCamera.svelte
<script lang="ts">
  import { onMount, onDestroy, setContext } from "svelte";
  import { createCamera } from "@voxcss/core";
  import type { SceneController, WallsMask } from "@voxcss/core";
  import type { AutoRotateOption, CameraState } from "@voxcss/core/camera";
  import type { HeadlessCameraHandle } from "@voxcss/core/headless";
  import { resolveInvertMultiplier, normalizePerspectiveValue } from "@voxcss/controller/utils";
  import { CONTROLLER_KEY } from "./context";

  export let zoom: number = 0.65;
  export let pan: number = 0;
  export let tilt: number = 0;
  export let rotX: number = 65;
  export let rotY: number = 45;
  export let invert: boolean | number = false;
  export let perspective: number | boolean = 8000;
  export let interactive: boolean = false;
  export let animate: AutoRotateOption = false;

  let container: HTMLDivElement | null = null;
  let controller: SceneController | null = null;
  let cameraHandle: HeadlessCameraHandle | null = null;
  let boxStyle: Record<string, string> = {};
  let walls: WallsMask | null = null;
  let cameraState: CameraState | null = null;
  let cursor = "default";
  let unsubscribeStyle: (() => void) | null = null;
  let unsubscribeCamera: (() => void) | null = null;

  function syncSnapshot() {
    if (!controller) return;
    boxStyle = controller.getBoxStyle();
    cameraState = controller.getCameraState();
    walls = controller.getWalls();
    cursor = interactive ? controller.getCursor() : "default";
  }

  onMount(() => {
    if (!container) return;
    const handle = createCamera({
      element: container,
      interactive,
      perspective: normalizePerspectiveValue(perspective),
      zoom,
      pan,
      tilt,
      rotX,
      rotY,
      invert,
      animate
    });
    cameraHandle = handle;
    controller = handle.controller;
    setContext(CONTROLLER_KEY, controller);
    syncSnapshot();
    unsubscribeStyle = controller.subscribeBoxStyle((style) => {
      boxStyle = style;
    });
    unsubscribeCamera = controller.subscribeCamera((state) => {
      cameraState = state;
      walls = controller?.getWalls() ?? null;
      cursor = interactive && controller ? controller.getCursor() : "default";
    });
  });

  onDestroy(() => {
    unsubscribeStyle?.();
    unsubscribeCamera?.();
    cameraHandle?.destroy();
    cameraHandle = null;
    controller = null;
  });

  $: if (cameraHandle) {
    cameraHandle.controller.updateCamera({ zoom, pan, tilt, rotX, rotY });
  }

  $: if (controller) {
    controller.setControls({ invert: resolveInvertMultiplier(invert) });
  }

  $: cameraHandle?.setInteractive(interactive);
  $: cameraHandle?.setPerspective(normalizePerspectiveValue(perspective));
  $: cameraHandle?.setAnimate(animate);

  export function startAutoRotate(value?: AutoRotateOption) {
    cameraHandle?.setAnimate(value ?? animate);
  }

  export function stopAutoRotate() {
    cameraHandle?.setAnimate(false);
  }
</script>

<div bind:this={container} class="voxcss-camera" style={`cursor:${cursor}`}>
  {#if controller}
    <slot boxStyle={boxStyle} cursor={cursor} walls={walls} controller={controller} camera={cameraState} />
  {/if}
</div>

// react/VoxCamera.tsx
import React, { useEffect, useLayoutEffect, useState, useRef, useImperativeHandle, forwardRef } from "react";
import type { CSSProperties, ReactNode } from "react";
import type { SceneController } from "@voxcss/controller/createSceneController";
import { createCamera } from "@voxcss/core";
import type { WallsMask } from "@voxcss/core";
import type { AutoRotateOption } from "@voxcss/core/camera";
import type { HeadlessCameraHandle } from "@voxcss/core/headless";
import { resolveInvertMultiplier, normalizePerspectiveValue } from "@voxcss/controller/utils";
import { SceneControllerContext } from "./context";

const DEFAULTS = {
  zoom: 0.65,
  pan: 0,
  tilt: 0,
  rotX: 65,
  rotY: 45,
  invert: false
};
const DEFAULT_PERSPECTIVE = 8000;

export interface CameraRenderContext {
  boxStyle: CSSProperties;
  cursor: string;
  walls: WallsMask;
  controller: SceneController;
  camera: ReturnType<SceneController["getCameraState"]>;
}

export interface VoxCameraProps {
  zoom?: number;
  pan?: number;
  tilt?: number;
  rotX?: number;
  rotY?: number;
  invert?: boolean | number;
  perspective?: number | boolean;
  interactive?: boolean;
  animate?: AutoRotateOption;
  children?: ReactNode | ((context: CameraRenderContext) => ReactNode);
}

export interface VoxCameraHandle {
  controller: SceneController;
  startAutoRotate(config?: AutoRotateOption): void;
  stopAutoRotate(): void;
}

export const VoxCamera = forwardRef<VoxCameraHandle, VoxCameraProps>(function VoxCamera(
  {
    zoom = DEFAULTS.zoom,
    pan = DEFAULTS.pan,
    tilt = DEFAULTS.tilt,
    rotX = DEFAULTS.rotX,
    rotY = DEFAULTS.rotY,
    invert = DEFAULTS.invert,
    perspective = DEFAULT_PERSPECTIVE,
    interactive = false,
    animate,
    children
  },
  ref
) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const cameraHandleRef = useRef<HeadlessCameraHandle | null>(null);
  const animateOptionRef = useRef<AutoRotateOption | undefined>(animate);
  const [controller, setController] = useState<SceneController | null>(null);
  const [boxStyle, setBoxStyle] = useState<Record<string, string>>({});
  const [cameraState, setCameraState] = useState(() => controller?.getCameraState());
  const [walls, setWalls] = useState(() => controller?.getWalls());
  const [cursor, setCursor] = useState("default");

  useLayoutEffect(() => {
    const node = containerRef.current;
    if (!node) return;
    const handle = createCamera({
      element: node,
      interactive,
      perspective: normalizePerspectiveValue(perspective),
      zoom,
      pan,
      tilt,
      rotX,
      rotY,
      invert,
      animate
    });
    cameraHandleRef.current = handle;
    setController(handle.controller);
    return () => {
      handle.destroy();
      cameraHandleRef.current = null;
      setController(null);
      setBoxStyle({});
      setCameraState(undefined);
      setWalls(undefined);
      setCursor("default");
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const handle = cameraHandleRef.current;
    if (!handle) return;
    handle.controller.updateCamera({ zoom, pan, tilt, rotX, rotY });
  }, [zoom, pan, tilt, rotX, rotY]);

  useEffect(() => {
    if (!controller) return;
    controller.setControls({ invert: resolveInvertMultiplier(invert) });
  }, [controller, invert]);

  useEffect(() => {
    cameraHandleRef.current?.setInteractive(interactive);
  }, [interactive]);

  useEffect(() => {
    cameraHandleRef.current?.setPerspective(normalizePerspectiveValue(perspective));
  }, [perspective]);

  useEffect(() => {
    animateOptionRef.current = animate;
    cameraHandleRef.current?.setAnimate(animate);
  }, [animate]);

  useEffect(() => {
    if (!controller) return;
    setBoxStyle(controller.getBoxStyle());
    setCameraState(controller.getCameraState());
    setWalls(controller.getWalls());
    setCursor(interactive ? controller.getCursor() : "default");
    const unsubscribeBox = controller.subscribeBoxStyle((style) => setBoxStyle(style));
    const unsubscribeCamera = controller.subscribeCamera((state) => {
      setCameraState(state);
      setWalls(controller.getWalls());
      setCursor(interactive ? controller.getCursor() : "default");
    });
    return () => {
      unsubscribeBox();
      unsubscribeCamera();
    };
  }, [controller, interactive]);

  useImperativeHandle(
    ref,
    () => ({
      controller: controller as SceneController,
      startAutoRotate(config?: AutoRotateOption) {
        const option = config ?? animateOptionRef.current;
        animateOptionRef.current = option;
        cameraHandleRef.current?.setAnimate(option);
      },
      stopAutoRotate() {
        cameraHandleRef.current?.setAnimate(false);
      }
    }),
    [controller]
  );

  const context: CameraRenderContext | null = controller
    ? {
        boxStyle,
        cursor,
        walls: walls ?? controller.getWalls(),
        controller,
        camera: cameraState ?? controller.getCameraState()
      }
    : null;

  const renderedChildren =
    controller && context
      ? typeof children === "function"
        ? (children as (ctx: CameraRenderContext) => ReactNode)(context)
        : children
      : null;

  return (
    <SceneControllerContext.Provider value={controller}>
      <div ref={containerRef} className="voxcss-camera" style={{ cursor }}>
        {renderedChildren}
      </div>
    </SceneControllerContext.Provider>
  );
});
