// svelte/VoxScene.svelte
<script lang="ts">
  import { getContext, onDestroy, onMount } from "svelte";
  import { createSceneHost } from "@voxcss/controller/createSceneHost";
  import { wallMasksEqual, inferGridDimensions } from "@voxcss/core";
  import type {
    SceneHost,
    SceneController,
    VoxelGrid,
    ShapeRenderer,
    WallsMask,
    VoxcssHooks,
    ProjectionMode
  } from "@voxcss/core";
  import { CONTROLLER_KEY } from "./context";

  export let voxels: VoxelGrid = [];
  export let rows: number | undefined = undefined;
  export let cols: number | undefined = undefined;
  export let depth: number | undefined = undefined;
  export let showWalls = false;
  export let showFloor = false;
  export let shapes: Record<string, ShapeRenderer> = {};
  export let hooks: VoxcssHooks | undefined = undefined;
export let projection: ProjectionMode | undefined = undefined;
export let dimetric = false;

  const controller = getContext<SceneController>(CONTROLLER_KEY);
  if (!controller) {
    throw new Error("voxcss: VoxScene must be used inside VoxCamera.");
  }

  let host: SceneHost | null = null;
  let container: HTMLDivElement | null = null;
  let lastVoxels: VoxelGrid = voxels;
  let walls: WallsMask = controller.getWalls();
  let boxStyle = controller.getBoxStyle();
  const unsubscribeStyle = controller.subscribeBoxStyle((style) => {
    boxStyle = style;
  });

  const unsubscribeCamera = controller.subscribeCamera(() => {
    const nextWalls = controller.getWalls();
    if (wallMasksEqual(walls, nextWalls)) {
      return;
    }
    walls = nextWalls;
  });

  onDestroy(() => {
    unsubscribeCamera?.();
    unsubscribeStyle?.();
    host?.destroy();
    host = null;
  });

  onMount(() => {
    host = createSceneHost({ shapes, hooks });
    if (container) {
      host.mount(container, voxels, buildContext());
    }
    lastVoxels = voxels;
    return () => {
      host?.destroy();
      host = null;
    };
  });

  function buildContext() {
    const inferred = inferGridDimensions(voxels);
    const depthValue = typeof depth === "number" ? depth : inferred.depth;
    const rowValue = typeof rows === "number" ? rows : inferred.rows;
    const colValue = typeof cols === "number" ? cols : inferred.cols;
    const projectionMode: ProjectionMode | undefined = dimetric ? "dimetric" : projection;
    controller.setProjection?.(projectionMode);
    return {
      rows: rowValue,
      cols: colValue,
      depth: depthValue,
      showWalls,
      showFloor,
      projection: projectionMode,
      walls,
      resolveTexture(name: string, face: string) {
        if (!name || name.startsWith("#")) return undefined;
        if (
          name.startsWith("/") ||
          name.startsWith("./") ||
          name.startsWith("../") ||
          name.startsWith("http://") ||
          name.startsWith("https://") ||
          name.includes(".")
        ) {
          return name;
        }
        return `textures/${name}/${name}-${face}.svg`;
      }
    };
  }

  function updateHost() {
    if (!host) return;
    const context = buildContext();
    if (lastVoxels !== voxels) {
      lastVoxels = voxels;
      host.update(voxels, context);
    } else {
      host.updateContext(context);
    }
  }

  $: inferredDims = inferGridDimensions(voxels);
  $: depthValue = typeof depth === "number" ? depth : inferredDims.depth;
  $: (() => {
    const rowValue = typeof rows === "number" ? rows : inferredDims.rows;
    const colValue = typeof cols === "number" ? cols : inferredDims.cols;
    controller.setDimensions({ rows: rowValue, cols: colValue, depth: depthValue });
  })();
  $: projection, updateHost();
  $: dimetric, updateHost();
  $: host?.setShapes(shapes);
  $: host?.setHooks(hooks);
</script>

<div
  bind:this={container}
  style={Object.entries(boxStyle)
    .map(([key, value]) => `${key}:${value}`)
    .join(";")}
>
</div>

// react/VoxScene.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import type { CSSProperties } from "react";
import { createSceneHost } from "@voxcss/controller/createSceneHost";
import type { SceneHost } from "@voxcss/controller/createSceneHost";
import type { SceneController } from "@voxcss/controller/createSceneController";
import { inferGridDimensions, wallMasksEqual } from "@voxcss/core";
import type {
  VoxelGrid,
  ShapeRenderer,
  WallsMask,
  VoxcssHooks,
  ProjectionMode
} from "@voxcss/core";
import { useSceneControllerContext } from "./context";

const DEFAULT_VOXELS: VoxelGrid = [];

export interface VoxSceneProps {
  voxels?: VoxelGrid;
  rows?: number;
  cols?: number;
  depth?: number;
  showWalls?: boolean;
  showFloor?: boolean;
  shapes?: Record<string, ShapeRenderer>;
  hooks?: VoxcssHooks;
  projection?: ProjectionMode;
  dimetric?: boolean;
}

export function VoxScene({
  voxels = DEFAULT_VOXELS,
  rows,
  cols,
  depth,
  showWalls = false,
  showFloor = false,
  shapes = {},
  hooks,
  projection,
  dimetric = false
}: VoxSceneProps) {
  const controller = useSceneControllerContext();
  const containerRef = useRef<HTMLDivElement | null>(null);
  const hostRef = useRef<SceneHost | null>(null);
  const wallsRef = useRef<WallsMask>(controller.getWalls());
  const prevVoxelsRef = useRef<VoxelGrid | null>(null);
  const [boxStyle, setBoxStyle] = useState<Record<string, string>>(() => controller.getBoxStyle());

  useEffect(() => controller.subscribeBoxStyle((style) => setBoxStyle(style)), [controller]);

  const buildContext = useCallback(() => {
    const inferred = inferGridDimensions(voxels);
    const depthValue = typeof depth === "number" ? depth : inferred.depth;
    const rowValue = typeof rows === "number" ? rows : inferred.rows;
    const colValue = typeof cols === "number" ? cols : inferred.cols;
    const projectionMode: ProjectionMode | undefined = dimetric ? "dimetric" : projection;
    controller.setProjection?.(projectionMode);
    return {
      rows: rowValue,
      cols: colValue,
      depth: depthValue,
      showWalls,
      showFloor,
      projection: projectionMode,
      walls: wallsRef.current,
      resolveTexture(name: string, face: string) {
        if (!name || name.startsWith("#")) return undefined;
        if (
          name.startsWith("/") ||
          name.startsWith("./") ||
          name.startsWith("../") ||
          name.startsWith("http://") ||
          name.startsWith("https://") ||
          name.includes(".")
        ) {
          return name;
        }
        return `textures/${name}/${name}-${face}.svg`;
      }
    };
  }, [rows, cols, depth, voxels, showWalls, showFloor, projection, dimetric, controller]);

  useEffect(() => {
    const host = createSceneHost({ shapes, hooks });
    hostRef.current = host;
    const node = containerRef.current;
    if (node) {
      host.mount(node, voxels, buildContext());
    }
    return () => host.destroy();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    const unsubscribe = controller.subscribeCamera(() => {
      const nextWalls = controller.getWalls();
      if (wallMasksEqual(wallsRef.current, nextWalls)) {
        return;
      }
      wallsRef.current = nextWalls;
      const host = hostRef.current;
      if (!host) return;
      host.updateContext(buildContext());
    });
    return unsubscribe;
  }, [controller, voxels, buildContext]);

  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    const context = buildContext();
    if (prevVoxelsRef.current !== voxels) {
      prevVoxelsRef.current = voxels;
      host.update(voxels, context);
    } else {
      host.updateContext(context);
    }
  }, [voxels, rows, cols, showWalls, showFloor, depth, projection, dimetric, buildContext]);

  useEffect(() => {
    hostRef.current?.setShapes(shapes);
  }, [shapes]);

  useEffect(() => {
    hostRef.current?.setHooks(hooks);
  }, [hooks]);

  useEffect(() => {
    const inferred = inferGridDimensions(voxels);
    const depthValue = typeof depth === "number" ? depth : inferred.depth;
    const rowValue = typeof rows === "number" ? rows : inferred.rows;
    const colValue = typeof cols === "number" ? cols : inferred.cols;
    controller.setDimensions({ rows: rowValue, cols: colValue, depth: depthValue });
  }, [controller, rows, cols, depth, voxels]);

  return <div ref={containerRef} style={boxStyle as CSSProperties} />;
}
