// svelte/VoxCamera.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import type { SceneController } from "@voxcss/controller/sceneController";
  import type { AutoRotateOption } from "@voxcss/core/camera";
  import { CAMERA_HOST_CLASS, type CameraComponentProps, type CameraSlotProps } from "@voxcss/controller/domBindings";
  import { mountCameraBinding } from "@voxcss/controller/domBindings";

  export let zoom: number | undefined;
  export let pan: number | undefined;
  export let tilt: number | undefined;
  export let rotX: number | undefined;
  export let rotY: number | undefined;
  export let invert: boolean | number | undefined;
  export let perspective: number | boolean | undefined;
  export let interactive: boolean | undefined;
  export let animate: AutoRotateOption | undefined;

  let cameraElement: HTMLDivElement | null = null;
  let controller: SceneController | null = null;
  let slotProps: CameraSlotProps | null = null;
  let cursor = "default";
  let teardown: ReturnType<typeof mountCameraBinding> | null = null;

  const currentProps = (): CameraComponentProps => ({
    zoom,
    pan,
    tilt,
    rotX,
    rotY,
    invert,
    interactive,
    perspective,
    animate
  });

  function cleanup() {
    teardown?.destroy();
    teardown = null;
    controller = null;
    slotProps = null;
    cursor = "default";
  }

  onMount(() => {
    if (!cameraElement) return;
    const props = currentProps();
    teardown = mountCameraBinding(
      cameraElement,
      props,
      (snapshot) => {
        if (!snapshot) {
          controller = null;
          slotProps = null;
          cursor = "default";
          return;
        }
        controller = snapshot.controller;
        slotProps = {
          boxStyle: snapshot.boxStyle,
          cursor: snapshot.cursor,
          walls: snapshot.walls,
          camera: snapshot.camera,
          controller: snapshot.controller
        };
        cursor = snapshot.cursor;
      },
      (nextCursor) => {
        cursor = nextCursor;
      }
    );
    return cleanup;
  });

  $: teardown?.update(currentProps());

  export function startAutoRotate(value?: AutoRotateOption) {
    teardown?.startAutoRotate(value);
  }

  export function stopAutoRotate() {
    teardown?.stopAutoRotate();
  }

  onDestroy(() => {
    cleanup();
  });
</script>

<div bind:this={cameraElement} class={CAMERA_HOST_CLASS} style={`cursor:${cursor}`}>
  {#if slotProps}
    <slot
      boxStyle={slotProps.boxStyle}
      cursor={slotProps.cursor}
      walls={slotProps.walls}
      controller={slotProps.controller}
      camera={slotProps.camera}
    />
  {/if}
</div>

// packages/voxcss/react/VoxCamera.tsx
import React, { forwardRef, useImperativeHandle, useMemo, useRef, useState, useLayoutEffect, useEffect } from "react";
import type { CSSProperties, ReactNode } from "react";
import type { SceneController } from "@layoutit/voxcss-core";
import {
  CAMERA_HOST_CLASS,
  type CameraComponentProps,
  type CameraSlotProps
} from "@layoutit/voxcss-html";
import type { AutoRotateOption } from "@layoutit/voxcss-core";
import { SceneControllerContext, useSceneControllerContext } from "./useBindings";
import { mountCameraBinding } from "@layoutit/voxcss-html";

export interface CameraChildRender {
  (context: CameraRenderContext): ReactNode;
}

export interface CameraRenderContext extends Omit<CameraSlotProps, "boxStyle"> {
  boxStyle: CSSProperties;
}

export interface VoxCameraHandle {
  controller: SceneController;
  startAutoRotate(config?: AutoRotateOption): void;
  stopAutoRotate(): void;
}

export type VoxCameraProps = CameraComponentProps & {
  children?: ReactNode | CameraChildRender;
};

export const VoxCamera = forwardRef<VoxCameraHandle, VoxCameraProps>(function VoxCamera(props, ref) {
  const { children, zoom, pan, tilt, rotX, rotY, invert, perspective, interactive, animate } = props;
  const cameraProps = useMemo(() => ({ zoom, pan, tilt, rotX, rotY, invert, perspective, interactive, animate }), [
    zoom,
    pan,
    tilt,
    rotX,
    rotY,
    invert,
    perspective,
    interactive,
    animate
  ]);

  const containerRef = useRef<HTMLDivElement | null>(null);
  const teardownRef = useRef<ReturnType<typeof mountCameraBinding> | null>(null);
  const latestProps = useRef(cameraProps);

  const [slotProps, setSlotProps] = useState<CameraSlotProps | null>(null);
  const [cursor, setCursor] = useState("default");

  useLayoutEffect(() => {
    const element = containerRef.current;
    if (!element) return;
    const options = latestProps.current;
    teardownRef.current = mountCameraBinding(
      element,
      options,
      (snapshot) => {
        setSlotProps(snapshot);
        setCursor(snapshot?.cursor ?? "default");
      },
      (nextCursor) => setCursor(nextCursor)
    );
    return () => {
      teardownRef.current?.destroy();
      teardownRef.current = null;
      setSlotProps(null);
      setCursor("default");
    };
  }, []);

  useEffect(() => {
    latestProps.current = cameraProps;
    teardownRef.current?.update(cameraProps);
  }, [cameraProps]);

  useImperativeHandle(
    ref,
    () => ({
      controller: controller ?? useSceneControllerContext(),
      startAutoRotate: (config?: AutoRotateOption) => {
        teardownRef.current?.startAutoRotate(config);
      },
      stopAutoRotate: () => {
        teardownRef.current?.stopAutoRotate();
      }
    }),
    [slotProps?.controller]
  );

  const controller = slotProps?.controller ?? null;

  const renderedChildren =
    slotProps && controller
      ? typeof children === "function"
        ? (children as CameraChildRender)(convertSlotProps(slotProps))
        : children
      : null;

  return (
    <SceneControllerContext.Provider value={controller}>
      <div ref={containerRef} className={CAMERA_HOST_CLASS} style={{ cursor }}>
        {renderedChildren}
      </div>
    </SceneControllerContext.Provider>
  );
});

function convertSlotProps(slotProps: CameraSlotProps): CameraRenderContext {
  return {
    ...slotProps,
    boxStyle: slotProps.boxStyle as CSSProperties
  };
}
